services:
  - type: web
    name: adv_santos
    env: python
    buildCommand: "./.render-build.sh && pip install -r requirements.txt"
    startCommand: gunicorn index:server
    envVars:
      - key: DASH_DEBUG
        value: 'False'
    plan: free
